### PR TITLE
Test the tests

### PR DESCRIPTION
**Pull request by sandaemc**

### CODE REVIEW

**Comment by nlabrador** [comment]
@sandaemc Just want to confirm. Will the content writers write the proof files?

**Comment by sandaemc** [comment]
@nlabrador Yes, but a proof-library must be built on top to ease creation of proofs. That is the direction.

**Comment by nlabrador** [comment]
I see. I get the idea now. Thanks

**Comment by sandaemc** [comment]
[Release changes for testing the tests](https://trello.com/c/Nexib3A9/3-release-changes-for-testing-the-tests)

**Comment by sandaemc** [comment]
@nlabrador @maraoarao

Please update you branch. You can now test your tests using:

```
./run.sh tests
```

Provided there is a counterpart `answers` file.

**Pull request merged**
